version: 2.1
jobs:
  build-and-test:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:20.11.0-browsers
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: Install PostgreSQL client and setup database
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
            createdb -h localhost d4adlocal -U postgres
      - run:
          name: Install required dependencies for Cypress
          command: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - restore_cache:
          keys:
            - node-deps-v2-{{ .Branch }}-{{ checksum "package.json" }}
            - node-deps-v2-{{ .Branch }}
            - node-deps-v2
      - run:
          name: Install Node.js dependencies
          command: npm install
      - save_cache:
          key: node-deps-v2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Node.js tests
          command: npm test
      - run:
          name: Execute feature tests script
          command: DB_ENV=$DB_ENV scripts/feature-tests.sh > feature-test-output.txt
          no_output_timeout: 30m
      - store_artifacts:
          path: feature-test-output.txt
      - store_artifacts:
          path: wiremock.log
      - store_artifacts:
          path: /home/circleci/.npm/_logs/*.log
      - store_artifacts:
          path: ~/project/frontend/cypress/videos
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy_dev:
    circleci_ip_ranges: true
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Install SSH
          command: sudo apt-get install -y openssh-client
      - add_ssh_keys:
          fingerprints:
            - "SHA256:UkBaGthILXKNTD7u0bbWle4fJwGE3thGwtiC3huxLAw"
      - run:
          name: SSH into EC2 and Deploy
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_IP \
              "cd d4ad && \
              git pull origin master && \
              ./scripts/install-all.sh && \
              ./scripts/db-migrate.sh && \
              rm -rf backend/dist/ && \
              ./scripts/build.sh"
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy_dev:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master